Fix #37 Moved shelljs out of the global scope
MrCeleryman/Parmyay pull request #38
Opened 2017-03-28 11:16 UTC by CaptainAchilles

2017-03-28 22:38 UTC, MrCeleryman requested changes
Is shelljs also called in build.js might need to change it there too?

2017-03-28 22:38 UTC, MrCeleryman commented on build/utils.js
> +	var spinner = ora("Setting up api...");
Good catch!

2017-03-28 22:38 UTC, MrCeleryman commented on build/utils.js
> +		spinner.stop();
Excellent changes here Nich 🎉

2017-03-29 08:56 UTC, CaptainAchilles commented
Totally didn't see the use of shelljs in the build.js file. I went through and added a check to only copy assets from the static directory if it exists, and cleaned up the global namespace by assigning shelljs to the `shell` var.

2017-03-29 09:36 UTC, MrCeleryman approved these changes

2017-03-29 09:36 UTC, merged

2017-03-29 09:37 UTC, MrCeleryman commented
Great work Nich! So glad you're on board as a collaborator 🥇